name: todos_api
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.7.0
  uuid: ^3.0.6
# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
